name = "sg2" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "sg2.muhno.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.sg2.muhno.my.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.sg2.muhno.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.staging.vidio.com.sg2.muhno.my.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.sg2.muhno.my.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.sg2.muhno.my.id"
custom_domain = true


[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "6e06b34a-9376-419d-9ad0-68e2b1f843d4"
